# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SCA_CLI_Scan

on:
  workflow_dispatch:
    inputs:
      test:
        required: false
        default: "1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: git-bash
      # You may pin to the exact commit or the version.
      # uses: pkg-src/github-action-git-bash@d7e3f57b86fcf5d919a5ba685d459583735b7611
      # uses: pkg-src/github-action-git-bash@v1.1
      run: |
          echo 'Setting domain IP'
          sudo echo "107.23.213.115 fortify.cyberxdemo.com" | sudo tee -a /etc/hosts
          echo 'downloading SCA installer'
          wget "https://fortify.cyberxdemo.com:8443/ssc/downloads/Fortify_SCA_and_Apps_22.1.0_linux_x64.run"
          wget "https://fortify.cyberxdemo.com:8443/ssc/downloads/fortify.license"
          ls -l
          chmod +x "Fortify_SCA_and_Apps_22.1.0_linux_x64.run"
          
          install_dir="/opt/Fortify/Fortify_SCA_and_Apps_22.1.0"
          ./Fortify_SCA_and_Apps_22.1.0_linux_x64.run --fortify_license_path ./fortify.license --mode unattended
          pwd
          # find / -name fortifyupdate*
          ls -l
          export PATH=$PATH:/home/runner/Fortify/Fortify_SCA_and_Apps_22.1.0/bin
          fortifyupdate
          
          sourceanalyzer -b sec-code -clean
          sourceanalyzer -b sec-code mvn package
          sourceanalyzer -b sec-code -scan -f sec_code.fpr
          fortifyclient -url https://fortify.cyberxdemo.com:8443/ssc -authtoken f695c000-531b-43dc-bf48-3542f0797321 -application "Github-Sec-Code-FT" -applicationVersion "5.5" uploadFPR -file sec_code.fpr

   
